FROM postgres:17

# Устанавливаем необходимые инструменты и PostGIS
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    postgis \
    postgresql-17-postgis-3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Создаем SQL скрипт, который создаст расширения для PostGIS
COPY init_postgis.sql /docker-entrypoint-initdb.d/

# Используем стандартную команду запуска
CMD ["docker-entrypoint.sh", "postgres"]
