
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1224
      POSTGRES_DB: stt_video_app
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data  # volume для сохранности данных

  redis:
    image: redis:latest
    networks:
      - backend

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # Для обращения к API из подписчика
      - "45127:45127" # Для WebUI
    command: server /data --console-address ":45127"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - backend

  video_handler_subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    platform: linux/arm64
    command: >
      bash -c "export PYTHONPATH=$(pwd) && python -m video_handle.video_handler_subscriber"
    networks:
      - backend
    volumes:
      - ./video_service.log:/app/video_service.log  # Добавить лог-файл
      - ./video_temp:/app/video_temp  # Общая папка для временных видео
      - ./user_logo:/app/user_logo  # Общая папка для логотипов пользователей
      - ./image_temp:/app/image_temp  # Общая папка для временных изображений
      - ./output_preview:/app/output_preview  # Общая папка для выводов превью
      - ./output_video:/app/output_video  # Общая папка для выводов видео
    environment:
      MINIO_ENDPOINT: minio:45127

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - ./video_service.log:/app/video_service.log
      - ./video_temp:/app/video_temp
      - ./user_logo:/app/user_logo
      - ./image_temp:/app/image_temp
      - ./output_preview:/app/output_preview
      - ./output_video:/app/output_video

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
