"""add new field user_link

Revision ID: 43fa88c095e2
Revises: 587c392bfbad
Create Date: 2025-03-29 11:06:28.699433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fa88c095e2'
down_revision: Union[str, None] = '587c392bfbad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('user_link', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['user_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'user_link')
    # ### end Alembic commands ###
