"""add partial unique indexes for video_url and preview_url

Revision ID: b6e50b7d2188
Revises: 
Create Date: 2025-03-02 22:30:24.726320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e50b7d2188'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_profiles_preview_url_key', 'user_profiles', type_='unique')
    op.drop_constraint('user_profiles_video_url_key', 'user_profiles', type_='unique')
    op.create_index('ix_user_profiles_preview_url_unique', 'user_profiles', ['preview_url'], unique=True, postgresql_where=sa.text('preview_url IS NOT NULL'))
    op.create_index('ix_user_profiles_video_url_unique', 'user_profiles', ['video_url'], unique=True, postgresql_where=sa.text('video_url IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_profiles_video_url_unique', table_name='user_profiles', postgresql_where=sa.text('video_url IS NOT NULL'))
    op.drop_index('ix_user_profiles_preview_url_unique', table_name='user_profiles', postgresql_where=sa.text('preview_url IS NOT NULL'))
    op.create_unique_constraint('user_profiles_video_url_key', 'user_profiles', ['video_url'])
    op.create_unique_constraint('user_profiles_preview_url_key', 'user_profiles', ['preview_url'])
    # ### end Alembic commands ###
